create table if not exists public.dsp_courier_shift_quality_report (
    id bigint generated by default as identity primary key,
    courier_id integer not null,
    courier_name text,
    work_date date not null,
    shift_key text not null,
    shift_name text,
    shift_start_at timestamp,
    shift_end_at timestamp,
    warehouse text,
    booking_code text,
    first_shift_of_day boolean not null default false,
    last_shift_of_day boolean not null default false,
    available_at timestamp,
    queue_started_at timestamp,
    route_id text,
    route_count integer not null default 0,
    route_type text not null default 'express' check (route_type in ('express', 'normal', 'regional')),
    assignment_mode text,
    address_count integer not null default 0,
    time_window_late_count integer not null default 0,
    planned_departure_at timestamp,
    planned_return_at timestamp,
    planned_route_minutes integer not null default 0,
    real_departure_at timestamp,
    real_return_at timestamp,
    queued_on_time boolean not null default false,
    no_late_time_window boolean not null default false,
    no_show boolean not null default false,
    no_show_reason text,
    late_order_cutoff_exception boolean not null default false,
    quality_ok boolean not null default false,
    source text not null default 'dsp_route_story',
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint dsp_courier_shift_quality_report_unique unique (courier_id, work_date, shift_key)
);

create index if not exists dsp_courier_shift_quality_report_courier_day_idx
    on public.dsp_courier_shift_quality_report (courier_id, work_date desc);

create index if not exists dsp_courier_shift_quality_report_quality_idx
    on public.dsp_courier_shift_quality_report (work_date, no_show, quality_ok);

alter table public.dsp_courier_shift_quality_report
    add column if not exists planned_route_minutes integer not null default 0,
    add column if not exists route_type text not null default 'express'
        check (route_type in ('express', 'normal', 'regional'));

grant all on table public.dsp_courier_shift_quality_report to service_role;
      

notify pgrst, 'reload schema';
