create table if not exists public.dsp_courier_quality_daily (
    id bigint generated by default as identity primary key,
    courier_id integer not null,
    courier_name text,
    work_date date not null,
    scope text not null default 'daily',
    shift_count integer not null default 0,
    show_count integer not null default 0,
    no_show_count integer not null default 0,
    late_shift_count integer not null default 0,
    route_count integer not null default 0,
    order_count integer not null default 0,
    delayed_order_count integer not null default 0,
    delay_percent numeric(8, 2) not null default 0,
    late_percent numeric(8, 2) not null default 0,
    no_show_percent numeric(8, 2) not null default 0,
    route_quality_bad_percent numeric(8, 2) not null default 0,
    compliance_score_percent numeric(8, 2) not null default 100,
    company_delay_bonus_huf integer not null default 0,
    courier_delay_bonus_huf integer not null default 0,
    company_compliance_bonus_huf integer not null default 0,
    courier_compliance_bonus_huf integer not null default 0,
    company_quality_bonus_total_huf integer not null default 0,
    courier_quality_bonus_total_huf integer not null default 0,
    delay_level integer not null default 1,
    route_quality_level integer not null default 1,
    source text not null default 'dsp_shift_quality',
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint dsp_courier_quality_daily_unique unique (courier_id, work_date)
);

create index if not exists dsp_courier_quality_daily_work_date_idx
    on public.dsp_courier_quality_daily (work_date desc, courier_id);

create index if not exists dsp_courier_quality_daily_quality_idx
    on public.dsp_courier_quality_daily (work_date desc, route_quality_level, delay_level);

alter table public.dsp_courier_quality_daily
    add column if not exists company_delay_bonus_huf integer not null default 0,
    add column if not exists courier_delay_bonus_huf integer not null default 0,
    add column if not exists company_compliance_bonus_huf integer not null default 0,
    add column if not exists courier_compliance_bonus_huf integer not null default 0,
    add column if not exists company_quality_bonus_total_huf integer not null default 0,
    add column if not exists courier_quality_bonus_total_huf integer not null default 0;

create table if not exists public.dsp_courier_quality_monthly (
    id bigint generated by default as identity primary key,
    courier_id integer not null,
    courier_name text,
    period_month date not null,
    scope text not null default 'monthly',
    shift_count integer not null default 0,
    show_count integer not null default 0,
    no_show_count integer not null default 0,
    late_shift_count integer not null default 0,
    route_count integer not null default 0,
    order_count integer not null default 0,
    delayed_order_count integer not null default 0,
    delay_percent numeric(8, 2) not null default 0,
    late_percent numeric(8, 2) not null default 0,
    no_show_percent numeric(8, 2) not null default 0,
    route_quality_bad_percent numeric(8, 2) not null default 0,
    compliance_score_percent numeric(8, 2) not null default 100,
    company_delay_bonus_huf integer not null default 0,
    courier_delay_bonus_huf integer not null default 0,
    company_compliance_bonus_huf integer not null default 0,
    courier_compliance_bonus_huf integer not null default 0,
    company_quality_bonus_total_huf integer not null default 0,
    courier_quality_bonus_total_huf integer not null default 0,
    delay_level integer not null default 1,
    route_quality_level integer not null default 1,
    source text not null default 'dsp_shift_quality',
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint dsp_courier_quality_monthly_unique unique (courier_id, period_month)
);

create index if not exists dsp_courier_quality_monthly_period_idx
    on public.dsp_courier_quality_monthly (period_month desc, courier_id);

create index if not exists dsp_courier_quality_monthly_quality_idx
    on public.dsp_courier_quality_monthly (period_month desc, route_quality_level, delay_level);

alter table public.dsp_courier_quality_monthly
    add column if not exists company_delay_bonus_huf integer not null default 0,
    add column if not exists courier_delay_bonus_huf integer not null default 0,
    add column if not exists company_compliance_bonus_huf integer not null default 0,
    add column if not exists courier_compliance_bonus_huf integer not null default 0,
    add column if not exists company_quality_bonus_total_huf integer not null default 0,
    add column if not exists courier_quality_bonus_total_huf integer not null default 0;

grant all on table public.dsp_courier_quality_daily to service_role;
grant all on table public.dsp_courier_quality_monthly to service_role;
grant usage, select on sequence public.dsp_courier_quality_daily_id_seq to service_role;
grant usage, select on sequence public.dsp_courier_quality_monthly_id_seq to service_role;

notify pgrst, 'reload schema';
