create table if not exists public.dsp_jitt_quality_bonus_matrix (
    id bigint generated by default as identity primary key,
    metric_type text not null check (metric_type in ('delay', 'compliance')),
    level_code integer not null check (level_code between 1 and 4),
    level_label text not null,
    courier_level_label text not null,
    day_type text not null default 'any',
    route_type text not null default 'any' check (route_type in ('express', 'normal', 'regional', 'any')),
    route_type_label text not null,
    warehouse_code text,
    threshold_min numeric(8, 4),
    threshold_max numeric(8, 4),
    threshold_min_inclusive boolean not null default true,
    threshold_max_inclusive boolean not null default true,
    duration_min_hours numeric(5, 4),
    duration_max_hours numeric(5, 4),
    duration_label text not null,
    company_amount_huf integer not null default 0 check (company_amount_huf >= 0),
    courier_amount_huf integer not null default 0 check (courier_amount_huf >= 0),
    calculation_unit text not null default 'per_route' check (calculation_unit in ('fixed', 'per_route', 'per_order', 'per_hour')),
    source text not null default 'manual',
    note text,
    valid_from date not null default date '2026-01-01',
    valid_to date,
    priority integer not null default 100,
    is_active boolean not null default true,
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

alter table public.dsp_jitt_quality_bonus_matrix
    add column if not exists courier_level_label text not null default '',
    drop constraint if exists dsp_jitt_quality_bonus_matrix_level_code_check,
    add constraint dsp_jitt_quality_bonus_matrix_level_code_check check (level_code between 1 and 4);

create index if not exists dsp_jitt_quality_bonus_matrix_lookup_idx
    on public.dsp_jitt_quality_bonus_matrix (
        metric_type,
        route_type,
        is_active,
        priority,
        threshold_min,
        threshold_max,
        duration_min_hours,
        duration_max_hours
    );

delete from public.dsp_jitt_quality_bonus_matrix
where source in ('jitt_contract_2026_image', 'jitt_contract_2026_matrix');

with metric_bands as (
    select *
    from (
        values
            ('delay', 1, 'Szint 1', 'JITT-1', null::numeric, 1.50::numeric, true, true),
            ('delay', 2, 'Szint 2', 'JITT-2', 1.51::numeric, 3.00::numeric, true, true),
            ('delay', 3, 'Szint 3', 'JITT-3', 3.01::numeric, 5.00::numeric, true, true),
            ('delay', 4, 'Szint 4', 'JITT-4', 5.01::numeric, null::numeric, true, true),
            ('compliance', 1, 'Szint 1', 'JITT-1', null::numeric, 2.00::numeric, true, true),
            ('compliance', 2, 'Szint 2', 'JITT-2', 2.01::numeric, 4.00::numeric, true, true),
            ('compliance', 3, 'Szint 3', 'JITT-3', 4.01::numeric, 10.00::numeric, true, true),
            ('compliance', 4, 'Szint 4', 'JITT-4', 10.01::numeric, null::numeric, true, true)
    ) as bands(
        metric_type,
        level_code,
        level_label,
        courier_level_label,
        threshold_min,
        threshold_max,
        threshold_min_inclusive,
        threshold_max_inclusive
    )
),
duration_bands as (
    select *
    from (
        values
            (1, null::numeric, 2.00::numeric, '<=2,0 ora', 'express', 'EXP', true,  1333, 666, 333, 0, 1333, 500, 250, 0),
            (2, 2.0001::numeric, 3.00::numeric, '3,0 ora', 'normal', 'CITY', true, 2000, 1000, 500, 0, 2000, 500, 250, 0),
            (3, 3.0001::numeric, 3.50::numeric, '3,5 ora', 'normal', 'CITY', true, 2333, 1166, 583, 0, 2333, 500, 500, 0),
            (4, 3.5001::numeric, 4.00::numeric, '4,0 ora', 'normal', 'CITY', true, 2666, 1333, 666, 0, 2666, 1000, 500, 0),
            (5, 4.0001::numeric, 4.50::numeric, '4,5 ora', 'normal', 'CITY', true, 3000, 1500, 750, 0, 3000, 1000, 500, 0),
            (6, 4.5001::numeric, 5.00::numeric, '5,0 ora', 'normal', 'CITY', true, 3333, 1666, 833, 0, 3000, 1000, 500, 0),
            (7, 5.0001::numeric, 5.50::numeric, '5,5 ora', 'regional', 'REGION', false, 3666, 1833, 916, 0, 3330, 1000, 500, 0),
            (8, 5.5001::numeric, 6.00::numeric, '6,0 ora', 'regional', 'REGION', false, 4000, 2000, 1000, 0, 3330, 1000, 500, 0)
    ) as durations(
        duration_order,
        duration_min_hours,
        duration_max_hours,
        duration_label,
        route_type,
        route_type_label,
        is_active,
        company_l1,
        company_l2,
        company_l3,
        company_l4,
        courier_l1,
        courier_l2,
        courier_l3,
        courier_l4
    )
)
insert into public.dsp_jitt_quality_bonus_matrix (
    metric_type,
    level_code,
    level_label,
    courier_level_label,
    day_type,
    route_type,
    route_type_label,
    threshold_min,
    threshold_max,
    threshold_min_inclusive,
    threshold_max_inclusive,
    duration_min_hours,
    duration_max_hours,
    duration_label,
    company_amount_huf,
    courier_amount_huf,
    calculation_unit,
    source,
    note,
    valid_from,
    priority,
    is_active
)
select
    metric_bands.metric_type,
    metric_bands.level_code,
    metric_bands.level_label,
    metric_bands.courier_level_label,
    'any',
    duration_bands.route_type,
    duration_bands.route_type_label,
    metric_bands.threshold_min,
    metric_bands.threshold_max,
    metric_bands.threshold_min_inclusive,
    metric_bands.threshold_max_inclusive,
    duration_bands.duration_min_hours,
    duration_bands.duration_max_hours,
    duration_bands.duration_label,
    case metric_bands.level_code
        when 1 then duration_bands.company_l1
        when 2 then duration_bands.company_l2
        when 3 then duration_bands.company_l3
        else duration_bands.company_l4
    end,
    case metric_bands.level_code
        when 1 then duration_bands.courier_l1
        when 2 then duration_bands.courier_l2
        when 3 then duration_bands.courier_l3
        else duration_bands.courier_l4
    end,
    'per_route',
    'jitt_contract_2026_matrix',
    'DSP/JITT quality matrix from the latest spreadsheet screenshot. Express and city are active; regional is stored but inactive.',
    date '2026-01-01',
    case when metric_bands.metric_type = 'delay' then 0 else 1000 end
        + metric_bands.level_code * 100
        + duration_bands.duration_order,
    duration_bands.is_active
from metric_bands
cross join duration_bands;

grant all on table public.dsp_jitt_quality_bonus_matrix to service_role;
grant usage, select on sequence public.dsp_jitt_quality_bonus_matrix_id_seq to service_role;

notify pgrst, 'reload schema';
