create table if not exists public.pwa_courier_route_notes (
    id bigint generated by default as identity primary key,
    courier_id text not null,
    courier_name text,
    work_date date not null,
    route_id text not null,
    note text not null default '',
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint pwa_courier_route_notes_unique unique (courier_id, work_date, route_id)
);

create index if not exists pwa_courier_route_notes_lookup_idx
    on public.pwa_courier_route_notes (courier_id, work_date desc, route_id);

grant all on table public.pwa_courier_route_notes to service_role;
grant usage, select on sequence public.pwa_courier_route_notes_id_seq to service_role;

notify pgrst, 'reload schema';
