create table if not exists public.pwa_courier_route_quality_report (
    id bigint generated by default as identity primary key,
    courier_id text not null,
    courier_name text,
    period_start date not null,
    work_date date not null,
    route_id text not null,
    warehouse_id integer,
    shift_key text,
    shift_start_at timestamptz,
    route_type text,
    route_assigned_at timestamptz,
    shift_available_at timestamptz,
    queue_started_at timestamptz,
    departed_at timestamptz,
    planned_return_at timestamptz,
    real_return_at timestamptz,
    queued_on_time boolean not null default false,
    no_late_stops boolean not null default false,
    quality_ok boolean not null default false,
    late_start_minutes integer not null default 0,
    late_stop_count integer not null default 0,
    late_stop_minutes integer not null default 0,
    same_checkin_group boolean not null default false,
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint pwa_courier_route_quality_report_unique unique (courier_id, work_date, route_id)
);

create index if not exists pwa_courier_route_quality_report_period_idx
    on public.pwa_courier_route_quality_report (period_start, courier_id, work_date desc);

create index if not exists pwa_courier_route_quality_report_shift_idx
    on public.pwa_courier_route_quality_report (courier_id, work_date, shift_key);

grant all on table public.pwa_courier_route_quality_report to service_role;
grant usage, select on sequence public.pwa_courier_route_quality_report_id_seq to service_role;

notify pgrst, 'reload schema';
