begin;

create table if not exists public.dsp_courier_quality_monthly (
    id bigint generated by default as identity primary key,
    courier_id integer not null,
    courier_name text,
    period_month date not null,
    shift_count integer not null default 0,
    no_show_count integer not null default 0,
    late_shift_count integer not null default 0,
    delayed_order_count integer not null default 0,
    company_delay_bonus_huf integer not null default 0,
    company_compliance_bonus_huf integer not null default 0,
    company_quality_bonus_total_huf integer not null default 0,
    courier_quality_bonus_total_huf integer not null default 0,
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    constraint dsp_courier_quality_monthly_snapshot_unique unique (courier_id, period_month)
);

create table if not exists settlement.courier_monthly_workload_summary (
    id uuid primary key default gen_random_uuid(),
    courier_id text not null,
    courier_name text,
    period_start date not null,
    period_end date not null,
    booked_shift_count integer not null default 0,
    advance_booked_shift_count integer not null default 0,
    giriton_shift_count integer not null default 0,
    completed_route_count integer not null default 0,
    order_count numeric not null default 0,
    muszakpro_source text,
    route_source text,
    updated_at timestamptz not null default now(),
    constraint courier_monthly_workload_summary_snapshot_unique unique (courier_id, period_start)
);

alter table public.dsp_courier_quality_monthly
    add column if not exists shift_count integer not null default 0,
    add column if not exists no_show_count integer not null default 0,
    add column if not exists late_shift_count integer not null default 0,
    add column if not exists delayed_order_count integer not null default 0,
    add column if not exists company_delay_bonus_huf integer not null default 0,
    add column if not exists company_compliance_bonus_huf integer not null default 0,
    add column if not exists company_quality_bonus_total_huf integer not null default 0,
    add column if not exists courier_quality_bonus_total_huf integer not null default 0;

alter table settlement.courier_monthly_workload_summary
    add column if not exists booked_shift_count integer not null default 0,
    add column if not exists advance_booked_shift_count integer not null default 0,
    add column if not exists giriton_shift_count integer not null default 0,
    add column if not exists completed_route_count integer not null default 0,
    add column if not exists order_count numeric not null default 0,
    add column if not exists muszakpro_source text,
    add column if not exists route_source text;

create index if not exists courier_settlement_summary_session_courier_idx
    on settlement.courier_settlement_summary (session_id, courier_id);

create index if not exists dsp_courier_quality_monthly_courier_period_idx
    on public.dsp_courier_quality_monthly (courier_id, period_month);

create or replace view settlement.vw_courier_month_profile_snapshot as
select
    summary.*,
    date_trunc('month', coalesce(summary.period_start, summary.period_end))::date as period_month,
    coalesce(quality.company_delay_bonus_huf, 0) as company_delay_bonus_huf,
    coalesce(quality.company_compliance_bonus_huf, 0) as company_compliance_bonus_huf,
    coalesce(quality.company_quality_bonus_total_huf, 0) as company_quality_bonus_total_huf,
    coalesce(quality.courier_quality_bonus_total_huf, 0) as courier_quality_bonus_total_huf,
    coalesce(quality.shift_count, 0) as quality_shift_count,
    coalesce(quality.no_show_count, 0) as quality_no_show_count,
    coalesce(quality.late_shift_count, 0) as quality_late_shift_count,
    coalesce(quality.delayed_order_count, 0) as quality_delayed_order_count,
    coalesce(workload.booked_shift_count, 0) as booked_shift_count,
    coalesce(workload.advance_booked_shift_count, 0) as advance_booked_shift_count,
    coalesce(workload.giriton_shift_count, 0) as giriton_shift_count,
    coalesce(workload.completed_route_count, summary.route_count, 0) as completed_route_count,
    coalesce(workload.order_count, summary.order_count, 0) as workload_order_count,
    coalesce(summary.company_base_rate_huf, 0) + coalesce(quality.company_quality_bonus_total_huf, 0) as contractor_total_huf
from settlement.courier_settlement_summary summary
left join public.dsp_courier_quality_monthly quality
    on quality.courier_id::text = summary.courier_id
    and quality.period_month = date_trunc('month', coalesce(summary.period_start, summary.period_end))::date
left join settlement.courier_monthly_workload_summary workload
    on workload.courier_id = summary.courier_id
    and workload.period_start = date_trunc('month', coalesce(summary.period_start, summary.period_end))::date;

grant select on settlement.vw_courier_month_profile_snapshot to service_role;
grant select on settlement.vw_courier_month_profile_snapshot to authenticated;

notify pgrst, 'reload schema';

commit;
