begin;

create schema if not exists settlement;
create extension if not exists pgcrypto;

alter table if exists settlement.courier_settlement_adjustment
    add column if not exists valid_from date,
    add column if not exists valid_to date,
    add column if not exists source_key text;

create table if not exists public.bill_jitt_invoice_monthly_adjustments (
    id bigint generated by default as identity primary key,
    billing_month date,
    worksheet_name text,
    courier_id text,
    driver_name text,
    bonus_huf numeric not null default 0,
    malus_huf numeric not null default 0,
    returned_route_huf numeric not null default 0,
    accepted_route_huf numeric not null default 0,
    source_total_huf numeric not null default 0,
    source_row_number integer,
    created_at timestamptz not null default now()
);

create table if not exists settlement.mobile_settlement_breakdown_overrides (
    period_start date not null,
    courier_id text not null,
    item_key text not null,
    item_label text not null,
    amount_value numeric not null default 0,
    amount_kind text not null default 'huf' check (amount_kind in ('huf', 'count')),
    note text,
    updated_by text,
    updated_at timestamptz not null default now(),
    primary key (period_start, courier_id, item_key)
);

create index if not exists idx_mobile_breakdown_overrides_courier_month
    on settlement.mobile_settlement_breakdown_overrides (courier_id, period_start);

create table if not exists public.peopleforce_documents (
    id uuid primary key default gen_random_uuid(),
    courier_id text,
    courier_name text,
    document_type text,
    document_month date,
    title text,
    file_name text,
    mime_type text,
    file_size integer,
    note text,
    uploaded_by text,
    uploaded_at timestamptz not null default now(),
    file_content_base64 text
);

create index if not exists peopleforce_documents_courier_month_type_idx
    on public.peopleforce_documents (courier_id, document_month, document_type, uploaded_at desc);

-- DB-side monthly audit layer for the legacy settlement page.
-- It keeps the old UI untouched, but makes the final paid/payable amount and
-- every bonus/malus/correction component queryable from SQL.

drop view if exists settlement.vw_legacy_payment_audit_summary;

create or replace view settlement.vw_legacy_payment_audit_summary as
with summary_base as (
    select
        s.session_id,
        coalesce(nullif(s.courier_id, ''), 'name:' || lower(trim(s.driver_name))) as courier_id,
        s.driver_name as courier_name,
        s.period_start,
        s.period_end,
        s.route_count,
        s.order_count,
        coalesce(s.company_base_rate_huf, 0) as company_base_rate_huf,
        coalesce(s.courier_base_rate_huf, 0) as courier_base_rate_huf,
        coalesce(s.tip_huf, 0) as tip_huf,
        coalesce(s.delay_bonus_huf, 0) as delay_bonus_huf,
        coalesce(s.compliance_bonus_huf, 0) as compliance_bonus_huf,
        coalesce(s.other_route_bonus_huf, 0) as other_route_bonus_huf,
        coalesce(s.route_bonus_total_huf, 0) as route_bonus_total_huf,
        coalesce(s.imported_bonus_huf, 0) as imported_bonus_huf,
        coalesce(s.manual_bonus_huf, 0) as manual_bonus_huf,
        coalesce(s.customer_rating_bonus_huf, 0) as customer_rating_bonus_huf,
        coalesce(abs(s.malus_huf), 0) as malus_huf,
        coalesce(abs(s.atm_deduction_huf), 0) as atm_deduction_huf,
        coalesce(abs(s.other_expense_huf), 0) as other_expense_huf,
        coalesce(s.payable_huf, 0) as calculated_payable_huf,
        s.calculated_at
    from settlement.courier_settlement_summary s
),
adjustment_totals as (
    select
        s.session_id,
        s.courier_id,
        s.period_start,
        sum(a.amount_huf) filter (where a.adjustment_type = 'bonus') as adjustment_bonus_huf,
        sum(a.amount_huf) filter (where a.adjustment_type = 'malus') as adjustment_malus_huf,
        sum(a.amount_huf) filter (where a.adjustment_type = 'customer_rating') as adjustment_customer_rating_huf,
        sum(a.amount_huf) filter (where a.adjustment_type = 'atm_deduction') as adjustment_atm_deduction_huf,
        sum(a.amount_huf) filter (where a.adjustment_type = 'other_expense') as adjustment_other_expense_huf,
        sum(a.amount_huf) filter (where a.adjustment_type in ('correction', 'manual_correction', 'correction_income')) as correction_income_huf,
        sum(a.amount_huf) filter (where a.adjustment_type in ('correction_deduction', 'manual_correction_deduction')) as correction_deduction_huf,
        count(*) as adjustment_rows_count,
        jsonb_agg(
            jsonb_build_object(
                'id', a.id,
                'type', a.adjustment_type,
                'amount_huf', a.amount_huf,
                'effective_date', a.effective_date,
                'valid_from', a.valid_from,
                'valid_to', a.valid_to,
                'note', a.note,
                'source_key', a.source_key
            )
            order by coalesce(a.effective_date, a.valid_from), a.created_at, a.id
        ) as adjustment_rows
    from summary_base s
    join settlement.courier_settlement_adjustment a
      on a.courier_id = s.courier_id
     and a.deleted_at is null
     and a.is_active
     and (a.session_id = s.session_id or a.session_id is null)
     and coalesce(a.valid_from, a.effective_date, s.period_start) <= s.period_end
     and coalesce(a.valid_to, a.effective_date, s.period_end) >= s.period_start
    group by s.session_id, s.courier_id, s.period_start
),
legacy_monthly_adjustments as (
    select
        date_trunc('month', m.billing_month::date)::date as period_month,
        coalesce(nullif(m.courier_id::text, ''), 'name:' || lower(trim(m.driver_name))) as courier_id,
        max(m.driver_name) as courier_name,
        sum(coalesce(m.bonus_huf, 0)) as legacy_sheet_bonus_huf,
        sum(abs(coalesce(m.malus_huf, 0))) as legacy_sheet_malus_huf,
        sum(abs(coalesce(m.returned_route_huf, 0))) as legacy_sheet_returned_route_huf,
        sum(coalesce(m.accepted_route_huf, 0)) as legacy_sheet_accepted_route_huf,
        sum(coalesce(m.source_total_huf, 0)) as legacy_sheet_source_total_huf,
        count(*) as legacy_sheet_rows_count,
        jsonb_agg(
            jsonb_build_object(
                'billing_month', m.billing_month,
                'worksheet_name', m.worksheet_name,
                'courier_id', m.courier_id,
                'driver_name', m.driver_name,
                'bonus_huf', m.bonus_huf,
                'malus_huf', m.malus_huf,
                'returned_route_huf', m.returned_route_huf,
                'accepted_route_huf', m.accepted_route_huf,
                'source_total_huf', m.source_total_huf,
                'source_row_number', m.source_row_number
            )
            order by m.billing_month, m.worksheet_name, m.source_row_number
        ) as legacy_sheet_rows
    from public.bill_jitt_invoice_monthly_adjustments m
    group by
        date_trunc('month', m.billing_month::date)::date,
        coalesce(nullif(m.courier_id::text, ''), 'name:' || lower(trim(m.driver_name)))
),
tig_mobile_totals as (
    select
        o.period_start,
        o.courier_id,
        max(o.amount_value) filter (where o.item_key = 'tig_final_total') as tig_final_total_huf,
        max(o.updated_at) as tig_updated_at,
        max(o.updated_by) as tig_updated_by,
        count(*) filter (where o.item_key like 'tig_%') as tig_rows_count,
        jsonb_agg(
            jsonb_build_object(
                'item_key', o.item_key,
                'item_label', o.item_label,
                'amount_value', o.amount_value,
                'amount_kind', o.amount_kind,
                'note', o.note,
                'updated_by', o.updated_by,
                'updated_at', o.updated_at
            )
            order by
                case when o.item_key = 'tig_final_total' then 1 else 0 end,
                o.item_key
        ) filter (where o.item_key like 'tig_%') as tig_rows
    from settlement.mobile_settlement_breakdown_overrides o
    group by o.period_start, o.courier_id
),
uploaded_invoices as (
    select distinct on (d.courier_id, date_trunc('month', d.document_month::date)::date)
        d.courier_id,
        date_trunc('month', d.document_month::date)::date as period_month,
        d.id as uploaded_invoice_document_id,
        d.title as uploaded_invoice_title,
        d.file_name as uploaded_invoice_file_name,
        d.note as uploaded_invoice_note,
        d.uploaded_at as uploaded_invoice_uploaded_at,
        d.uploaded_by as uploaded_invoice_uploaded_by,
        coalesce(
            (regexp_match(
                concat_ws(' ', d.note, d.title, d.file_name),
                '(?:számlaszám|szamlaszam|sorszám|sorszam)\s*:?\s*([A-Za-z0-9/_-]{3,})',
                'i'
            ))[1],
            (regexp_match(
                concat_ws(' ', d.note, d.title, d.file_name),
                '\m([A-Z]{1,5}[-_/]?\d{3,})\M',
                'i'
            ))[1],
            ''
        ) as uploaded_invoice_number,
        coalesce(
            nullif(regexp_replace(
                replace(replace(coalesce((regexp_match(
                    d.note,
                    'brutt[óo]\s+[öo]sszesen\s*:?\s*([0-9\s.,]+)\s*Ft',
                    'i'
                ))[1], ''), ' ', ''), ',', '.'),
                '[^0-9.]',
                '',
                'g'
            ), '')::numeric,
            nullif(regexp_replace(
                replace(replace(coalesce((regexp_match(
                    d.note,
                    '[öo]sszeg\s*:?\s*([0-9\s.,]+)\s*Ft',
                    'i'
                ))[1], ''), ' ', ''), ',', '.'),
                '[^0-9.]',
                '',
                'g'
            ), '')::numeric,
            0
        ) as uploaded_invoice_amount_huf
    from public.peopleforce_documents d
    where lower(coalesce(d.document_type, '')) = 'invoice'
       or lower(concat_ws(' ', d.document_type, d.title, d.file_name)) like '%számla%'
       or lower(concat_ws(' ', d.document_type, d.title, d.file_name)) like '%szamla%'
    order by
        d.courier_id,
        date_trunc('month', d.document_month::date)::date,
        d.uploaded_at desc,
        d.id desc
),
closure_latest as (
    select distinct on (c.courier_id, c.period_start, c.period_end)
        c.courier_id,
        c.period_start,
        c.period_end,
        c.session_id,
        c.status as closure_status,
        c.payable_huf as closure_payable_huf,
        c.invoice_number,
        c.payment_note,
        c.bank_account_number,
        c.recipient_name,
        c.closed_at,
        c.closed_by,
        c.reopened_at,
        c.reopened_by,
        c.snapshot
    from settlement.courier_monthly_closure c
    order by
        c.courier_id,
        c.period_start,
        c.period_end,
        c.updated_at desc,
        c.created_at desc
)
select
    s.session_id,
    s.period_start,
    s.period_end,
    s.courier_id,
    s.courier_name,
    s.route_count,
    s.order_count,
    s.company_base_rate_huf,
    s.courier_base_rate_huf,
    s.tip_huf,
    s.delay_bonus_huf,
    s.compliance_bonus_huf,
    s.other_route_bonus_huf,
    s.route_bonus_total_huf,
    s.imported_bonus_huf,
    s.manual_bonus_huf,
    coalesce(l.legacy_sheet_bonus_huf, 0) as legacy_sheet_bonus_huf,
    coalesce(l.legacy_sheet_malus_huf, 0) as legacy_sheet_malus_huf,
    coalesce(l.legacy_sheet_returned_route_huf, 0) as legacy_sheet_returned_route_huf,
    coalesce(l.legacy_sheet_accepted_route_huf, 0) as legacy_sheet_accepted_route_huf,
    coalesce(l.legacy_sheet_source_total_huf, 0) as legacy_sheet_source_total_huf,
    s.customer_rating_bonus_huf + coalesce(a.adjustment_customer_rating_huf, 0) as customer_rating_bonus_huf,
    coalesce(a.adjustment_bonus_huf, 0) as adjustment_bonus_huf,
    coalesce(a.adjustment_malus_huf, 0) as adjustment_malus_huf,
    coalesce(a.adjustment_atm_deduction_huf, 0) as adjustment_atm_deduction_huf,
    coalesce(a.adjustment_other_expense_huf, 0) as adjustment_other_expense_huf,
    coalesce(a.correction_income_huf, 0) as correction_income_huf,
    coalesce(a.correction_deduction_huf, 0) as correction_deduction_huf,
    coalesce(a.correction_income_huf, 0) - coalesce(a.correction_deduction_huf, 0) as correction_net_huf,
    s.malus_huf + coalesce(a.adjustment_malus_huf, 0) as malus_huf,
    s.atm_deduction_huf + coalesce(a.adjustment_atm_deduction_huf, 0) as atm_deduction_huf,
    s.other_expense_huf + coalesce(a.adjustment_other_expense_huf, 0) as other_expense_huf,
    (
        s.route_bonus_total_huf
        + s.imported_bonus_huf
        + s.manual_bonus_huf
        + s.customer_rating_bonus_huf
        + coalesce(a.adjustment_customer_rating_huf, 0)
        + coalesce(a.adjustment_bonus_huf, 0)
    ) as total_bonus_huf,
    (
        s.malus_huf
        + s.atm_deduction_huf
        + s.other_expense_huf
        + coalesce(a.adjustment_malus_huf, 0)
        + coalesce(a.adjustment_atm_deduction_huf, 0)
        + coalesce(a.adjustment_other_expense_huf, 0)
    ) as total_deduction_huf,
    (
        s.imported_bonus_huf
        + s.manual_bonus_huf
        + s.customer_rating_bonus_huf
        + coalesce(a.adjustment_customer_rating_huf, 0)
        + coalesce(a.adjustment_bonus_huf, 0)
        - s.malus_huf
        - coalesce(a.adjustment_malus_huf, 0)
    ) as bonus_malus_net_huf,
    s.calculated_payable_huf
        + coalesce(a.adjustment_bonus_huf, 0)
        + coalesce(a.adjustment_customer_rating_huf, 0)
        + coalesce(a.correction_income_huf, 0)
        - coalesce(a.adjustment_malus_huf, 0)
        - coalesce(a.adjustment_atm_deduction_huf, 0)
        - coalesce(a.adjustment_other_expense_huf, 0)
        - coalesce(a.correction_deduction_huf, 0) as current_payable_huf,
    case when c.closure_status = 'done' then coalesce(c.closure_payable_huf, s.calculated_payable_huf) else 0 end as paid_huf,
    c.closure_payable_huf,
    c.closure_status,
    c.invoice_number,
    c.payment_note,
    c.bank_account_number,
    c.recipient_name,
    c.closed_at,
    c.closed_by,
    c.reopened_at,
    c.reopened_by,
    coalesce(t.tig_final_total_huf, 0) as tig_final_total_huf,
    coalesce(t.tig_rows_count, 0) as tig_rows_count,
    coalesce(t.tig_rows, '[]'::jsonb) as tig_rows,
    t.tig_updated_at,
    t.tig_updated_by,
    i.uploaded_invoice_document_id,
    i.uploaded_invoice_number,
    i.uploaded_invoice_amount_huf,
    i.uploaded_invoice_title,
    i.uploaded_invoice_file_name,
    i.uploaded_invoice_note,
    i.uploaded_invoice_uploaded_at,
    i.uploaded_invoice_uploaded_by,
    coalesce(a.adjustment_rows_count, 0) as adjustment_rows_count,
    coalesce(a.adjustment_rows, '[]'::jsonb) as adjustment_rows,
    coalesce(l.legacy_sheet_rows_count, 0) as legacy_sheet_rows_count,
    coalesce(l.legacy_sheet_rows, '[]'::jsonb) as legacy_sheet_rows,
    jsonb_build_object(
        'base_huf', coalesce(nullif(c.snapshot ->> 'base_huf', '')::numeric, s.courier_base_rate_huf),
        'tip_huf', coalesce(nullif(c.snapshot ->> 'tip_huf', '')::numeric, s.tip_huf),
        'delay_bonus_huf', coalesce(nullif(c.snapshot ->> 'delay_bonus_huf', '')::numeric, s.delay_bonus_huf),
        'compliance_bonus_huf', coalesce(nullif(c.snapshot ->> 'compliance_bonus_huf', '')::numeric, s.compliance_bonus_huf),
        'bonus_huf', coalesce(nullif(c.snapshot ->> 'bonus_huf', '')::numeric, s.imported_bonus_huf + s.manual_bonus_huf),
        'customer_rating_huf', coalesce(nullif(c.snapshot ->> 'customer_rating_huf', '')::numeric, s.customer_rating_bonus_huf),
        'malus_huf', coalesce(nullif(c.snapshot ->> 'malus_huf', '')::numeric, s.malus_huf),
        'atm_deduction_huf', coalesce(nullif(c.snapshot ->> 'atm_deduction_huf', '')::numeric, s.atm_deduction_huf),
        'other_expense_huf', coalesce(nullif(c.snapshot ->> 'other_expense_huf', '')::numeric, s.other_expense_huf),
        'payable_huf', coalesce(nullif(c.snapshot ->> 'payable_huf', '')::numeric, c.closure_payable_huf, s.calculated_payable_huf)
    ) as closure_snapshot_amounts,
    s.calculated_at,
    now() as refreshed_at
from summary_base s
left join adjustment_totals a
  on a.session_id = s.session_id
 and a.courier_id = s.courier_id
 and a.period_start = s.period_start
left join legacy_monthly_adjustments l
  on l.courier_id = s.courier_id
 and l.period_month = date_trunc('month', s.period_start)::date
left join tig_mobile_totals t
  on t.courier_id = s.courier_id
 and t.period_start = s.period_start
left join uploaded_invoices i
  on i.courier_id = s.courier_id
 and i.period_month = date_trunc('month', s.period_start)::date
left join closure_latest c
  on c.courier_id = s.courier_id
 and c.period_start = s.period_start
 and c.period_end = s.period_end;

create table if not exists settlement.legacy_payment_audit_snapshot (
    id uuid primary key default gen_random_uuid(),
    session_id uuid,
    period_start date not null,
    period_end date,
    courier_id text not null,
    courier_name text,
    route_count integer not null default 0,
    order_count numeric not null default 0,
    company_base_rate_huf numeric not null default 0,
    courier_base_rate_huf numeric not null default 0,
    tip_huf numeric not null default 0,
    delay_bonus_huf numeric not null default 0,
    compliance_bonus_huf numeric not null default 0,
    other_route_bonus_huf numeric not null default 0,
    route_bonus_total_huf numeric not null default 0,
    imported_bonus_huf numeric not null default 0,
    manual_bonus_huf numeric not null default 0,
    legacy_sheet_bonus_huf numeric not null default 0,
    legacy_sheet_malus_huf numeric not null default 0,
    legacy_sheet_returned_route_huf numeric not null default 0,
    legacy_sheet_accepted_route_huf numeric not null default 0,
    legacy_sheet_source_total_huf numeric not null default 0,
    customer_rating_bonus_huf numeric not null default 0,
    adjustment_bonus_huf numeric not null default 0,
    adjustment_malus_huf numeric not null default 0,
    adjustment_atm_deduction_huf numeric not null default 0,
    adjustment_other_expense_huf numeric not null default 0,
    correction_income_huf numeric not null default 0,
    correction_deduction_huf numeric not null default 0,
    correction_net_huf numeric not null default 0,
    malus_huf numeric not null default 0,
    atm_deduction_huf numeric not null default 0,
    other_expense_huf numeric not null default 0,
    total_bonus_huf numeric not null default 0,
    total_deduction_huf numeric not null default 0,
    bonus_malus_net_huf numeric not null default 0,
    current_payable_huf numeric not null default 0,
    paid_huf numeric not null default 0,
    closure_payable_huf numeric,
    closure_status text,
    invoice_number text,
    payment_note text,
    bank_account_number text,
    recipient_name text,
    closed_at timestamptz,
    closed_by text,
    reopened_at timestamptz,
    reopened_by text,
    tig_final_total_huf numeric not null default 0,
    tig_rows_count integer not null default 0,
    tig_rows jsonb not null default '[]'::jsonb,
    tig_updated_at timestamptz,
    tig_updated_by text,
    uploaded_invoice_document_id uuid,
    uploaded_invoice_number text,
    uploaded_invoice_amount_huf numeric not null default 0,
    uploaded_invoice_title text,
    uploaded_invoice_file_name text,
    uploaded_invoice_note text,
    uploaded_invoice_uploaded_at timestamptz,
    uploaded_invoice_uploaded_by text,
    adjustment_rows_count integer not null default 0,
    adjustment_rows jsonb not null default '[]'::jsonb,
    legacy_sheet_rows_count integer not null default 0,
    legacy_sheet_rows jsonb not null default '[]'::jsonb,
    closure_snapshot_amounts jsonb not null default '{}'::jsonb,
    calculated_at timestamptz,
    refreshed_at timestamptz not null default now()
);

alter table settlement.legacy_payment_audit_snapshot
    add column if not exists legacy_sheet_bonus_huf numeric not null default 0,
    add column if not exists legacy_sheet_malus_huf numeric not null default 0,
    add column if not exists legacy_sheet_returned_route_huf numeric not null default 0,
    add column if not exists legacy_sheet_accepted_route_huf numeric not null default 0,
    add column if not exists legacy_sheet_source_total_huf numeric not null default 0,
    add column if not exists tig_final_total_huf numeric not null default 0,
    add column if not exists tig_rows_count integer not null default 0,
    add column if not exists tig_rows jsonb not null default '[]'::jsonb,
    add column if not exists tig_updated_at timestamptz,
    add column if not exists tig_updated_by text,
    add column if not exists uploaded_invoice_document_id uuid,
    add column if not exists uploaded_invoice_number text,
    add column if not exists uploaded_invoice_amount_huf numeric not null default 0,
    add column if not exists uploaded_invoice_title text,
    add column if not exists uploaded_invoice_file_name text,
    add column if not exists uploaded_invoice_note text,
    add column if not exists uploaded_invoice_uploaded_at timestamptz,
    add column if not exists uploaded_invoice_uploaded_by text,
    add column if not exists legacy_sheet_rows_count integer not null default 0,
    add column if not exists legacy_sheet_rows jsonb not null default '[]'::jsonb;

create unique index if not exists legacy_payment_audit_snapshot_uidx
    on settlement.legacy_payment_audit_snapshot (
        (coalesce(session_id, '00000000-0000-0000-0000-000000000000'::uuid)),
        courier_id,
        period_start
    );

create index if not exists legacy_payment_audit_snapshot_period_idx
    on settlement.legacy_payment_audit_snapshot (period_start, period_end, closure_status);

create or replace function settlement.refresh_legacy_payment_audit_snapshot(
    p_period_start date default null,
    p_period_end date default null
)
returns integer
language plpgsql
security definer
set search_path = settlement, public
as $$
declare
    v_count integer;
begin
    insert into settlement.legacy_payment_audit_snapshot (
        session_id, period_start, period_end, courier_id, courier_name, route_count, order_count,
        company_base_rate_huf, courier_base_rate_huf, tip_huf, delay_bonus_huf,
        compliance_bonus_huf, other_route_bonus_huf, route_bonus_total_huf,
        imported_bonus_huf, manual_bonus_huf, legacy_sheet_bonus_huf,
        legacy_sheet_malus_huf, legacy_sheet_returned_route_huf,
        legacy_sheet_accepted_route_huf, legacy_sheet_source_total_huf,
        customer_rating_bonus_huf,
        adjustment_bonus_huf, adjustment_malus_huf, adjustment_atm_deduction_huf,
        adjustment_other_expense_huf, correction_income_huf, correction_deduction_huf,
        correction_net_huf, malus_huf, atm_deduction_huf, other_expense_huf,
        total_bonus_huf, total_deduction_huf, bonus_malus_net_huf,
        current_payable_huf, paid_huf, closure_payable_huf, closure_status,
        invoice_number, payment_note, bank_account_number, recipient_name,
        closed_at, closed_by, reopened_at, reopened_by,
        tig_final_total_huf, tig_rows_count, tig_rows, tig_updated_at, tig_updated_by,
        uploaded_invoice_document_id, uploaded_invoice_number, uploaded_invoice_amount_huf,
        uploaded_invoice_title, uploaded_invoice_file_name, uploaded_invoice_note,
        uploaded_invoice_uploaded_at, uploaded_invoice_uploaded_by,
        adjustment_rows_count, adjustment_rows, legacy_sheet_rows_count,
        legacy_sheet_rows, closure_snapshot_amounts,
        calculated_at, refreshed_at
    )
    select
        session_id, period_start, period_end, courier_id, courier_name, route_count, order_count,
        company_base_rate_huf, courier_base_rate_huf, tip_huf, delay_bonus_huf,
        compliance_bonus_huf, other_route_bonus_huf, route_bonus_total_huf,
        imported_bonus_huf, manual_bonus_huf, legacy_sheet_bonus_huf,
        legacy_sheet_malus_huf, legacy_sheet_returned_route_huf,
        legacy_sheet_accepted_route_huf, legacy_sheet_source_total_huf,
        customer_rating_bonus_huf,
        adjustment_bonus_huf, adjustment_malus_huf, adjustment_atm_deduction_huf,
        adjustment_other_expense_huf, correction_income_huf, correction_deduction_huf,
        correction_net_huf, malus_huf, atm_deduction_huf, other_expense_huf,
        total_bonus_huf, total_deduction_huf, bonus_malus_net_huf,
        current_payable_huf, paid_huf, closure_payable_huf, closure_status,
        invoice_number, payment_note, bank_account_number, recipient_name,
        closed_at, closed_by, reopened_at, reopened_by,
        tig_final_total_huf, tig_rows_count, tig_rows, tig_updated_at, tig_updated_by,
        uploaded_invoice_document_id, uploaded_invoice_number, uploaded_invoice_amount_huf,
        uploaded_invoice_title, uploaded_invoice_file_name, uploaded_invoice_note,
        uploaded_invoice_uploaded_at, uploaded_invoice_uploaded_by,
        adjustment_rows_count, adjustment_rows, legacy_sheet_rows_count,
        legacy_sheet_rows, closure_snapshot_amounts,
        calculated_at, now()
    from settlement.vw_legacy_payment_audit_summary
    where (p_period_start is null or period_start >= p_period_start)
      and (p_period_end is null or period_end <= p_period_end)
    on conflict (
        (coalesce(session_id, '00000000-0000-0000-0000-000000000000'::uuid)),
        courier_id,
        period_start
    )
    do update set
        period_end = excluded.period_end,
        courier_name = excluded.courier_name,
        route_count = excluded.route_count,
        order_count = excluded.order_count,
        company_base_rate_huf = excluded.company_base_rate_huf,
        courier_base_rate_huf = excluded.courier_base_rate_huf,
        tip_huf = excluded.tip_huf,
        delay_bonus_huf = excluded.delay_bonus_huf,
        compliance_bonus_huf = excluded.compliance_bonus_huf,
        other_route_bonus_huf = excluded.other_route_bonus_huf,
        route_bonus_total_huf = excluded.route_bonus_total_huf,
        imported_bonus_huf = excluded.imported_bonus_huf,
        manual_bonus_huf = excluded.manual_bonus_huf,
        legacy_sheet_bonus_huf = excluded.legacy_sheet_bonus_huf,
        legacy_sheet_malus_huf = excluded.legacy_sheet_malus_huf,
        legacy_sheet_returned_route_huf = excluded.legacy_sheet_returned_route_huf,
        legacy_sheet_accepted_route_huf = excluded.legacy_sheet_accepted_route_huf,
        legacy_sheet_source_total_huf = excluded.legacy_sheet_source_total_huf,
        customer_rating_bonus_huf = excluded.customer_rating_bonus_huf,
        adjustment_bonus_huf = excluded.adjustment_bonus_huf,
        adjustment_malus_huf = excluded.adjustment_malus_huf,
        adjustment_atm_deduction_huf = excluded.adjustment_atm_deduction_huf,
        adjustment_other_expense_huf = excluded.adjustment_other_expense_huf,
        correction_income_huf = excluded.correction_income_huf,
        correction_deduction_huf = excluded.correction_deduction_huf,
        correction_net_huf = excluded.correction_net_huf,
        malus_huf = excluded.malus_huf,
        atm_deduction_huf = excluded.atm_deduction_huf,
        other_expense_huf = excluded.other_expense_huf,
        total_bonus_huf = excluded.total_bonus_huf,
        total_deduction_huf = excluded.total_deduction_huf,
        bonus_malus_net_huf = excluded.bonus_malus_net_huf,
        current_payable_huf = excluded.current_payable_huf,
        paid_huf = excluded.paid_huf,
        closure_payable_huf = excluded.closure_payable_huf,
        closure_status = excluded.closure_status,
        invoice_number = excluded.invoice_number,
        payment_note = excluded.payment_note,
        bank_account_number = excluded.bank_account_number,
        recipient_name = excluded.recipient_name,
        closed_at = excluded.closed_at,
        closed_by = excluded.closed_by,
        reopened_at = excluded.reopened_at,
        reopened_by = excluded.reopened_by,
        tig_final_total_huf = excluded.tig_final_total_huf,
        tig_rows_count = excluded.tig_rows_count,
        tig_rows = excluded.tig_rows,
        tig_updated_at = excluded.tig_updated_at,
        tig_updated_by = excluded.tig_updated_by,
        uploaded_invoice_document_id = excluded.uploaded_invoice_document_id,
        uploaded_invoice_number = excluded.uploaded_invoice_number,
        uploaded_invoice_amount_huf = excluded.uploaded_invoice_amount_huf,
        uploaded_invoice_title = excluded.uploaded_invoice_title,
        uploaded_invoice_file_name = excluded.uploaded_invoice_file_name,
        uploaded_invoice_note = excluded.uploaded_invoice_note,
        uploaded_invoice_uploaded_at = excluded.uploaded_invoice_uploaded_at,
        uploaded_invoice_uploaded_by = excluded.uploaded_invoice_uploaded_by,
        adjustment_rows_count = excluded.adjustment_rows_count,
        adjustment_rows = excluded.adjustment_rows,
        legacy_sheet_rows_count = excluded.legacy_sheet_rows_count,
        legacy_sheet_rows = excluded.legacy_sheet_rows,
        closure_snapshot_amounts = excluded.closure_snapshot_amounts,
        calculated_at = excluded.calculated_at,
        refreshed_at = now();

    get diagnostics v_count = row_count;
    return v_count;
end;
$$;

grant select on settlement.vw_legacy_payment_audit_summary to service_role;
grant select, insert, update, delete on settlement.legacy_payment_audit_snapshot to service_role;
grant execute on function settlement.refresh_legacy_payment_audit_snapshot(date, date) to service_role;

drop view if exists settlement.vw_legacy_tig_invoice_audit;

create or replace view settlement.vw_legacy_tig_invoice_audit as
with settlement_months as (
    select distinct
        coalesce(nullif(s.courier_id, ''), 'name:' || lower(trim(s.driver_name))) as courier_id,
        s.driver_name as courier_name,
        s.period_start,
        s.period_end
    from settlement.courier_settlement_summary s
),
tig as (
    select
        o.courier_id,
        o.period_start,
        max(o.amount_value) filter (where o.item_key = 'tig_final_total') as regi_rendszer_tig_osszeg,
        max(o.updated_at) as tig_updated_at,
        jsonb_agg(
            jsonb_build_object(
                'item_key', o.item_key,
                'item_label', o.item_label,
                'amount_value', o.amount_value,
                'note', o.note,
                'updated_at', o.updated_at
            )
            order by case when o.item_key = 'tig_final_total' then 1 else 0 end, o.item_key
        ) filter (where o.item_key like 'tig_%') as tig_rows
    from settlement.mobile_settlement_breakdown_overrides o
    where o.item_key like 'tig_%'
    group by o.courier_id, o.period_start
),
invoice_documents as (
    select distinct on (d.courier_id, date_trunc('month', d.document_month::date)::date)
        d.courier_id,
        date_trunc('month', d.document_month::date)::date as period_start,
        d.id as uploaded_invoice_document_id,
        coalesce(
            (regexp_match(
                concat_ws(' ', d.note, d.title, d.file_name),
                '(?:számlaszám|szamlaszam|sorszám|sorszam)\s*:?\s*([A-Za-z0-9/_-]{3,})',
                'i'
            ))[1],
            (regexp_match(
                concat_ws(' ', d.note, d.title, d.file_name),
                '\m([A-Z]{1,5}[-_/]?\d{3,})\M',
                'i'
            ))[1],
            ''
        ) as feltoltott_szamla_szam,
        coalesce(
            nullif(regexp_replace(
                replace(replace(coalesce((regexp_match(
                    d.note,
                    'brutt[óo]\s+[öo]sszesen\s*:?\s*([0-9\s.,]+)\s*Ft',
                    'i'
                ))[1], ''), ' ', ''), ',', '.'),
                '[^0-9.]',
                '',
                'g'
            ), '')::numeric,
            nullif(regexp_replace(
                replace(replace(coalesce((regexp_match(
                    d.note,
                    '[öo]sszeg\s*:?\s*([0-9\s.,]+)\s*Ft',
                    'i'
                ))[1], ''), ' ', ''), ',', '.'),
                '[^0-9.]',
                '',
                'g'
            ), '')::numeric,
            0
        ) as feltoltott_szamla_osszeg,
        d.title as feltoltott_szamla_cim,
        d.file_name as feltoltott_szamla_fajl,
        d.note as feltoltott_szamla_megjegyzes,
        d.uploaded_at as feltoltott_szamla_feltoltve
    from public.peopleforce_documents d
    where lower(coalesce(d.document_type, '')) = 'invoice'
       or lower(concat_ws(' ', d.document_type, d.title, d.file_name)) like '%számla%'
       or lower(concat_ws(' ', d.document_type, d.title, d.file_name)) like '%szamla%'
    order by
        d.courier_id,
        date_trunc('month', d.document_month::date)::date,
        d.uploaded_at desc,
        d.id desc
)
select
    m.courier_id,
    m.courier_name,
    m.period_start,
    m.period_end,
    coalesce(t.regi_rendszer_tig_osszeg, 0) as regi_rendszer_tig_osszeg,
    coalesce(i.feltoltott_szamla_szam, '') as feltoltott_szamla_szam,
    coalesce(i.feltoltott_szamla_osszeg, 0) as feltoltott_szamla_osszeg,
    i.uploaded_invoice_document_id,
    i.feltoltott_szamla_cim,
    i.feltoltott_szamla_fajl,
    i.feltoltott_szamla_megjegyzes,
    i.feltoltott_szamla_feltoltve,
    t.tig_updated_at,
    coalesce(t.tig_rows, '[]'::jsonb) as tig_rows
from settlement_months m
left join tig t
  on t.courier_id = m.courier_id
 and t.period_start = m.period_start
left join invoice_documents i
  on i.courier_id = m.courier_id
 and i.period_start = m.period_start;

grant select on settlement.vw_legacy_tig_invoice_audit to service_role;

notify pgrst, 'reload schema';

commit;
